export const locations = [
  { value: "Kota Jakarta", label: "Kota Jakarta" },
  { value: "Kota Bandung", label: "Kota Bandung" },
  { value: "Kota Surabaya", label: "Kota Surabaya" },
  { value: "Kota Yogyakarta", label: "Kota Yogyakarta" },
  { value: "Kota Denpasar", label: "Kota Denpasar" },
  { value: "Kota Medan", label: "Kota Medan" },
  { value: "Kota Makassar", label: "Kota Makassar" },
  { value: "Kota Semarang", label: "Kota Semarang" },
  { value: "Kota Palembang", label: "Kota Palembang" },
  { value: "Kota Malang", label: "Kota Malang" },
  { value: "Kota Manado", label: "Kota Manado" },
  { value: "Kota Bandar Lampung", label: "Kota Bandar Lampung" },
  { value: "Kota Surakarta (Solo)", label: "Kota Surakarta (Solo)" },
  { value: "Kota Batam", label: "Kota Batam" },
  { value: "Kota Pontianak", label: "Kota Pontianak" },
  { value: "Kota Ambon", label: "Kota Ambon" },
  { value: "Kota Kupang", label: "Kota Kupang" },
  { value: "Kota Bengkulu", label: "Kota Bengkulu" },
  { value: "Kota Padang", label: "Kota Padang" },
  { value: "Kota Banjarmasin", label: "Kota Banjarmasin" },
  { value: "Kota Tangerang", label: "Kota Tangerang" },
  { value: "Kota Bekasi", label: "Kota Bekasi" },
  { value: "Kabupaten Semarang", label: "Kabupaten Semarang" },
  { value: "Kabupaten Sidoarjo", label: "Kabupaten Sidoarjo" },
  { value: "Kabupaten Malang", label: "Kabupaten Malang" },
  { value: "Kabupaten Tangerang", label: "Kabupaten Tangerang" },
  { value: "Kabupaten Barito Kuala", label: "Kabupaten Barito Kuala" },
  { value: "Kabupaten Bekasi", label: "Kabupaten Bekasi" },
  { value: "Kabupaten Lampung Timur", label: "Kabupaten Lampung Timur" },
  { value: "Kabupaten Kepulauan Seribu", label: "Kabupaten Kepulauan Seribu" },
  // Tambahkan kota dan kabupaten lainnya sesuai kebutuhan
];
